plugins:
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes" 
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

title: Arnau Montagud personal page
description: Resources, figures and supplementary material of works.
name: "Arnau Montagud"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
