remote_theme: "mmistakes/minimal-mistakes" 
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-remote-theme

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

author:
  name   : "Arnau Montagud"
#  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Systems Biology and Data analyses"
  email  : # optional
  uri    : "https://www.researchgate.net/profile/Arnau_Montagud"
  home   : # null (default), "absolute or relative url to link to author home"
  
title: Arnau Montagud personal page
description: "Resources, figures and supplementary material of works."
name: "Arnau Montagud"
